name: Maven CI/CD

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  build_and_test:

   uses: ros132/Reusabletemplate/.github/workflows/resuable_template.yml@main
   with:
     file_path: pom.xml
