name: MVN build, SAST and SCA 

on:
  push:
    branches: [ "develop" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "develop" ]

jobs:
 BuildWithGitHubActions:

   uses: ros132/Reusabletemplate/.github/workflows/reusable_template.yml
   
   with:
     file_path: pom.xml
