name: Maven CI/CD

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Installing Git keaks 
      run : |
        wget -q -O gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
        ls -l
        tar -xzvf gitleaks.tar.gz
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/
        
    - name: Run git leaks
      run : |
         gitleaks detect --redact
     
        
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven
    
    - name: Buildproject with Maven
      run: mvn -B package --file pom.xml -e
    - name:  OWASP Dependency-Check download
      run: |
       wget -q -O dependency-check-8.4.0-release.zip  https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
       ls -l
       unzip -qq dependency-check-8.4.0-release.zip   

    - name: Run the OWASP Dependency-Check
      run: ./dependency-check/bin/dependency-check.sh --scan ./ --format HTML --project "Dependencychecker_DevOpsTest" --out ./report   
   
    - name: OWASP Dependency-Check Report Upload
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: ./report

    - name: FindSecBugs    Download
      run: |
       wget -q -O findsecbugs-cli-1.12.0.zip https://github.com/find-sec-bugs/find-sec-bugs/releases/download/version-1.12.0/findsecbugs-cli-1.12.0.zip 
       unzip -qq findsecbugs-cli-1.12.0.zip
       chmod 755 findsecbugs.sh 
       chmod +x findsecbugs.sh
       ls -l
    

    - name: Run FindSecBugs
      run: ./findsecbugs.sh -progress -output findsecbugs-results.html -html target/*.jar

    - name: FindSecBugs Report Upload
      uses: actions/upload-artifact@v2
      with:
        name: findsecbugs-report
        path: findsecbugs-results.html
