name: MVN build, SAST and SCA 

on:
 workflow_call:
  inputs:
    file_path:
      required: true
      type: string

jobs:
  build_and_test:

   uses: ros132/Reusabletemplate/.github/workflows/reusable_template.yml@develop
   with:
     file_path: pom.xml
